name: hive_project
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

  #form builder=====
  form_builder_validators: ^7.6.1
  flutter_form_builder: ^7.1.1
  form_builder_extra_fields: ^7.1.0
  form_builder_image_picker:
    git:
      url: git@github.com:Bdaya-Dev/form_builder_image_picker.git
      ref: main
  #form builder=====
  # hive =======
  hive: ^2.0.4
  hive_flutter: ^1.1.0
  path_provider: ^2.0.9
  # hive =======
  get: 4.6.1
  dio: ^4.0.4
  uuid: ^3.0.6
  flutter_zoom_drawer: ^2.3.1
  switcher_button: ^0.0.4

dev_dependencies:
  # hive =======
  build_runner: ^2.1.7
  hive_generator: ^1.1.2
  # hive =======
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/animations/
flutter_intl:
  enabled: true
